# Generated by Django 6.1.1 on 2026-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('flr', 'Forest Landscape Restoration & Nurseries'), ('community', 'Community Action & Cooperatives'), ('education', 'Education & Graduations'), ('health', 'Healthcare & Family Planning'), ('leadership', 'Leadership & Field Visits')], default='flr', max_length=50)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback or local static photo URL', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_taken', models.CharField(blank=True, default='2024-2026', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='check-circle', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact Statistic',
                'verbose_name_plural': 'Impact Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='Strategic Partner', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('flr', 'Landscape Restoration & Environment'), ('evangelism', 'Evangelism & Biblical Education'), ('child_women', 'Child Protection & Women Empowerment'), ('health', 'Health, Nutrition & HIV Eradication'), ('agriculture', 'Sustainable Agriculture & Cooperatives'), ('education', 'Education & Vocational Training')], default='flr', max_length=50)),
                ('summary', models.TextField(help_text='Short summary displayed on cards and previews')),
                ('description', models.TextField(help_text='Detailed description of the program and its impact')),
                ('icon', models.CharField(default='tree', help_text='Icon identifier (e.g. tree, cross, shield, heart, sprouter)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback static image or CDN URL', max_length=500)),
                ('target_beneficiaries', models.CharField(blank=True, default='Vulnerable households, women, youth', max_length=255)),
                ('location', models.CharField(blank=True, default='Gatsibo, Rutsiro, Nyarugenge, Nyanza', max_length=255)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program / Activity',
                'verbose_name_plural': 'Programs & Activities',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('location', models.CharField(default='Gatsibo District, Rwanda', max_length=150)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Farmer Testimonial',
                'verbose_name_plural': 'Farmer Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
