# Generated by Django 6.0.4 on 2026-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Movement for Christ in Rwanda (MPCR)', max_length=200)),
                ('org_name_fr', models.CharField(blank=True, default='Mouvement Pour Christ au Rwanda', max_length=200)),
                ('footer_about', models.TextField(blank=True)),
                ('legal_badge', models.CharField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('postal_box', models.CharField(blank=True, max_length=120)),
                ('phone_primary', models.CharField(blank=True, max_length=40)),
                ('phone_primary_raw', models.CharField(blank=True, max_length=40)),
                ('phone_secondary', models.CharField(blank=True, max_length=40)),
                ('phone_secondary_raw', models.CharField(blank=True, max_length=40)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=40)),
                ('whatsapp_message', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('focus_items', models.TextField(blank=True, help_text='One focus item per line')),
                ('footer_copyright', models.CharField(blank=True, max_length=255)),
                ('footer_tagline', models.CharField(blank=True, max_length=255)),
                ('social_handle', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('programs', 'Programs'), ('gallery', 'Gallery'), ('contact', 'Contact')], db_index=True, max_length=40)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('list', 'List'), ('image', 'Image')], default='text', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('image_url', models.CharField(blank=True, help_text='Static path or external URL fallback', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Page section',
                'verbose_name_plural': 'Page sections',
                'ordering': ['page', 'order', 'key'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
