# Generated by Django 6.0.4 on 2026-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_website_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('evangelism', 'Evangelism'), ('social', 'Social (well being)'), ('economic', 'Economic'), ('development', 'Development')], default='evangelism', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('evangelism', 'Evangelism'), ('social', 'Social (well being)'), ('economic', 'Economic'), ('development', 'Development')], default='evangelism', max_length=50),
        ),
    ]
