# Generated by Django 6.0.4 on 2026-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remap_content_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished photos stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='impactstat',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished stats stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished partners stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished programs stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished testimonials stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive slides stay in the dashboard but are hidden from the public site.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive members stay in the dashboard but are hidden from the public site.'),
        ),
    ]
