# Generated by Django 6.0.4 on 2026-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_content_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='date_taken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Fallback or local static photo URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
