"""Default editable website content keyed by page and section."""

PAGES = {
    "home": "Home",
    "about": "About",
    "programs": "Programs",
    "gallery": "Gallery",
    "contact": "Contact",
}

# (page, key, label, field_type, default_value, order)
# field_type: text | textarea | list | image
SECTION_DEFAULTS = [
    # Home — Hero
    ("home", "hero_title", "Hero title", "text", "Mouvent Pour Christe", 10),
    ("home", "hero_title_accent", "Hero title accent", "text", "au Rwanda ( MPCR )", 20),
    ("home", "hero_tagline", "Hero tagline", "textarea", '"Roho nzima itura mu mubiri muzima" — A healthy spirit lives in a healthy body.', 30),
    ("home", "hero_text", "Hero introduction", "textarea", "Movement for Christ in Rwanda (MPCR) is a legally registered Christian non-governmental organization committed to holistic evangelism, sustainable agriculture, child protection, community health, and forest landscape restoration across Rwanda.", 40),
    ("home", "hero_cta_primary", "Hero primary button label", "text", "Explore Our Programs", 50),
    ("home", "hero_cta_secondary", "Hero secondary button label", "text", "Contact Us", 60),
    ("home", "hero_card_title", "Hero card title", "text", "Our Foundation", 70),
    ("home", "hero_card_ref", "Hero card scripture reference", "text", "John 3:16 / Jean 3:16", 80),
    ("home", "hero_card_quote", "Hero card quote", "textarea", '"That whoever believes in HIM should not perish but have eternal life."\nAfin que tout homme qui croit en LUI ne périsse pas mais ait la vie éternelle: CHRIST.', 90),
    ("home", "hero_features", "Hero feature bullets (one per line, Title|Detail)", "list", "Accredited NGO:|Legal Compliance No. 166/2023 under Law No 06/2012\nFLR Leader:|Restoring 105+ ha in Gatsibo with TerraFund & WRI\nChurch Alliance:|Partnering with over 25 churches nationwide\nHeadquarters:|Nyamirambo Sector, Nyarugenge District, Kigali City", 100),
    # Home — Profile
    ("home", "profile_badge", "Profile section badge", "text", "Organizational Profile", 110),
    ("home", "profile_title", "Profile section title", "text", "Who We Are", 120),
    ("home", "profile_text_1", "Profile paragraph 1", "textarea", "Mouvement Pour Christ au Rwanda (MPCR) is a faith-based non-governmental organization working in Rwanda. It was created out of a deep Christian conviction that faith must be demonstrated through practical action and holistic human upliftment.", 130),
    ("home", "profile_text_2", "Profile paragraph 2", "textarea", "Our approach integrates the message of Christ with sustainable socio-economic development. We walk alongside rural and urban communities to strengthen family stability, safeguard vulnerable children, equip youth with income-generating skills, empower women through cooperatives, protect the natural environment, and foster community health.", 140),
    ("home", "profile_quote", "Profile quote", "textarea", "“Roho nzima ituruka mu mubiri muzima” — A healthy spirit lives in a healthy body", 150),
    ("home", "profile_image", "Profile image", "image", "images/ngororero-headquarters.png", 160),
    # Home — Section headers
    ("home", "programs_badge", "Programs badge", "text", "What We Do", 170),
    ("home", "programs_title", "Programs title", "text", "Our Key Programs & Activities", 180),
    ("home", "programs_subtitle", "Programs subtitle", "textarea", "Combining spiritual nourishment with impactful social, environmental, and economic initiatives across Rwandan communities.", 190),
    ("home", "gallery_badge", "Gallery badge", "text", "Visual Impact", 200),
    ("home", "gallery_title", "Gallery title", "text", "Activities & Field Photos", 210),
    ("home", "gallery_subtitle", "Gallery subtitle", "textarea", "Glimpses into our tree nurseries, cropland agroforestry, livestock awards, educational seminars, and community mobilizations.", 220),
    ("home", "team_badge", "Team badge", "text", "Our Team", 230),
    ("home", "team_title", "Team title", "text", "The People Behind MPCR", 240),
    ("home", "team_subtitle", "Team subtitle", "textarea", "A committed leadership and field team guiding evangelism, community development, and landscape restoration across Rwanda.", 250),
    ("home", "partners_badge", "Partners badge", "text", "Partners", 260),
    ("home", "partners_title", "Partners title", "text", "Organizations We Work With", 270),
    ("home", "cta_title", "Bottom CTA title", "text", "Partner With Us in Transforming Rwanda", 280),
    ("home", "cta_text", "Bottom CTA text", "textarea", "Whether you represent a church community, donor institution, development cooperative, or volunteer group, your collaboration makes a lasting impact.", 290),
    # About
    ("about", "banner_badge", "Banner badge", "text", "Our History & Identity", 10),
    ("about", "banner_title", "Banner title", "text", "About MPCR", 20),
    ("about", "banner_text", "Banner text", "textarea", "Mouvement Pour Christ au Rwanda (Movement for Christ in Rwanda) is a religious non-governmental organization dedicated to preaching the Gospel and advancing socio-economic transformation.", 30),
    ("about", "history_badge", "History badge", "text", "Historical Background", 40),
    ("about", "history_title", "History title", "text", "Rooted in Kigali, Reaching Across the Nation", 50),
    ("about", "history_text_1", "History paragraph 1", "textarea", "MPCR started its grassroots mission at Kinyinya in Gasabo District, Kigali City. Conceived as a response to both the spiritual thirst and the practical socio-economic vulnerabilities of rural and peri-urban populations, the organization has grown into an impactful nationwide institution.", 60),
    ("about", "history_text_2", "History paragraph 2", "textarea", "The organization is governed by its official statutes and is fully subject to the provisions of Law No. 06/2012 of 17/02/2012 governing Civil Society Organizations and Faith-Based Organizations (FBOs) in the Republic of Rwanda. MPCR was granted its official Legal Personality Certificate of Compliance No. 166/2023 by the Rwanda Governance Board (RGB).", 70),
    ("about", "office_title", "Office box title", "text", "Head Office Location", 80),
    ("about", "office_text", "Office box text", "textarea", "The MPCR national head office is situated at Kigali City, Nyarugenge District, Nyamirambo Sector, providing strategic administrative coordination for all field programs and regional initiatives.", 90),
    ("about", "faith_title", "Faith card title", "text", "Christian Faith & Doctrine", 100),
    ("about", "faith_ref", "Faith scripture reference", "text", "John 3:16 / Jean 3:16", 110),
    ("about", "faith_quote", "Faith quote", "textarea", '"That whoever believes in HIM should not perish but have eternal life."\n"Afin que tout homme qui croit en LUI ne périsse pas mais ait la vie éternelle: CHRIST."', 120),
    ("about", "faith_text", "Faith paragraph", "textarea", "We affirm that the Gospel of Jesus Christ brings total redemption—restoring humanity's spiritual relationship with the Creator while motivating compassionate service to the poor, the brokenhearted, and the marginalized.", 130),
    ("about", "identity_badge", "Vision/Mission badge", "text", "What We Stand For", 140),
    ("about", "identity_title", "Vision/Mission title", "text", "Vision, Mission & Guiding Identity", 150),
    ("about", "identity_subtitle", "Vision/Mission subtitle", "textarea", 'Anchored in our guiding principle: "Roho nzima itura mu mubiri muzima" (A healthy spirit lives in a healthy body).', 160),
    ("about", "vision_title", "Vision heading", "text", "Our Vision", 170),
    ("about", "vision_text", "Vision text", "textarea", 'Being a Faith Christian Organization leading positive change by preaching the gospel, promoting good living, economic development, and sustainable development because "A healthy spirit lives in a healthy body."', 180),
    ("about", "mission_title", "Mission heading", "text", "Our Mission", 190),
    ("about", "mission_text", "Mission text", "textarea", "To make Christ known and transform the lives of the people through evangelism, activities that improve the lives of the people, increase economic capacity, and promote sustainable development.", 200),
    ("about", "objectives_title", "Objectives title", "text", "Objectives", 210),
    ("about", "general_objective_title", "General objective heading", "text", "General Objective", 220),
    ("about", "general_objective", "General objective text", "textarea", "Promoting evangelism based on actions that address real problems of the people, in their well-being, economy and sustainable development.", 230),
    ("about", "specific_objectives_title", "Specific objectives heading", "text", "Specific Objectives", 240),
    ("about", "specific_objectives", "Specific objectives (one per line)", "list", "To evangelize youth and children\nTo integrate children and youth in epidemic diseases eradication\nTo fight against all forms of violence against children and women\nTo promote environment\nTo promote vocational trainings and cooperatives\nTo promote child rights\nTo reinforce income generating projects\nTo promote care and social events\nTo combat HIV in communities", 250),
    ("about", "values_title", "Core values title", "text", "Our Core Values (Indangagaciro)", 260),
    ("about", "core_values", "Core values (Title|Description per line)", "list", "Gukunda Imana no Kuyubaha|Devoted love and reverent fear of God guiding every decision, stewardship practice, and interpersonal interaction.\nGukorera mu Mucyo|Transparency and open accountability toward beneficiaries, government authorities, donor partners, and churches.\nUrukundo n'Impuhwe|Unconditional Christian love and compassion, reaching out especially to the most vulnerable, widows, orphans, and prisoners.\nUbumwe n'Ubufatanye|Unity, mutual respect, teamwork, and strong collaborative alliances across communities and civil society organizations.\nUbunyangamugayo|Uncompromising honesty, moral uprightness, and trustworthy financial and institutional stewardship.\nIterambere Rirambye|Sustainable development integrating environmental restoration with economic resilience for enduring community prosperity.", 270),
    # Programs
    ("programs", "banner_title", "Banner title", "text", "Our Programs", 10),
    ("programs", "banner_text", "Banner text", "textarea", "Comprehensive Interventions Empowering Rwandan Communities in Spirit, Mind, and Livelihood", 20),
    ("programs", "section_badge", "Section badge", "text", "Integrated Action", 30),
    ("programs", "section_title", "Section title", "text", "Community Transformation", 40),
    ("programs", "section_subtitle", "Section subtitle", "textarea", "MPCR designs and implements initiatives that meet urgent grassroots needs while building long-term community self-reliance.", 50),
    ("programs", "framework_badge", "Framework badge", "text", "Implementation Framework", 60),
    ("programs", "framework_title", "Framework title", "text", "Strategies & Target Beneficiaries", 70),
    ("programs", "framework_subtitle", "Framework subtitle", "textarea", "How MPCR drives sustainable grassroots mobilization and lasting community ownership.", 80),
    ("programs", "strategies_title", "Strategies heading", "text", "Core Delivery Strategies", 90),
    ("programs", "strategies", "Strategies (Title|Detail per line)", "list", "Christian Cinema & Road Shows:|Mobile open-air screenings conveying gospel truths and public health messages.\nEvangelization Campaigns:|Intensive community preaching, revival seminars, and youth fellowship rallies.\nLobby & Advocacy:|Defending the rights of women, child protection, and land restoration compliance.\nCapacity Building:|Training Child Protection Committees (CPCs), gender counselors, and farmer facilitators.\nDecentralized Nurseries:|Producing quality agroforestry and fruit seedlings directly within intervention sectors.", 100),
    ("programs", "beneficiaries_title", "Beneficiaries heading", "text", "Priority Target Beneficiaries", 110),
    ("programs", "beneficiaries", "Beneficiaries (Title|Detail per line)", "list", "Churches & Congregations:|Equipping pastors, Sunday school teachers, and faith youth leaders.\nChildren & University Students:|Fostering child protection, scholarships, and Christian values.\nWomen & Widows:|Income-generating cooperatives, livestock incentives, and cookstoves.\nPrisoners, Refugees & Informal Couples:|Pastoral reconciliation, counseling, and social reintegration.\nSmallholder Farmers & Cooperatives:|Training champion farmers in tree maintenance, soil care, and agroforestry.", 120),
    # Gallery
    ("gallery", "banner_badge", "Banner badge", "text", "Visual Chronicle", 10),
    ("gallery", "banner_title", "Banner title", "text", "Project & Activity Gallery", 20),
    ("gallery", "banner_text", "Banner text", "textarea", "Capturing real field milestones: tree nursery seedlings, agroforestry croplands, livestock awards, higher education graduations, and healthcare outreaches across Rwanda.", 30),
    # Contact
    ("contact", "banner_badge", "Banner badge", "text", "Get in Touch", 10),
    ("contact", "banner_title", "Banner title", "text", "Contact MPCR", 20),
    ("contact", "banner_text", "Banner text", "textarea", "We welcome inquiries, partnership proposals, church collaboration, prayer requests, and community support. Reach out to our coordination team.", 30),
    ("contact", "intro_badge", "Intro badge", "text", "Headquarters & Contacts", 40),
    ("contact", "intro_title", "Intro title", "text", "Let's Start a Conversation", 50),
    ("contact", "intro_text", "Intro text", "textarea", "Our national secretariat in Kigali coordinates operations across all districts. Feel free to reach out via phone, email, WhatsApp, or through our contact form.", 60),
    ("contact", "form_title", "Form title", "text", "Send Us a Message", 70),
    ("contact", "form_text", "Form text", "textarea", "Fill out the form below and we will get back to you promptly.", 80),
    ("contact", "hours_text", "Office hours note", "text", "Available Monday – Friday: 8:00 AM – 5:00 PM CAT", 90),
]

HERO_SLIDE_DEFAULTS = [
    "images/hero/slide-1.png",
    "images/hero/slide-2.png",
    "images/hero/slide-3.png",
    "images/hero/slide-4.png",
    "images/hero/slide-5.png",
    "images/hero/slide-6.png",
    "images/hero/slide-7.png",
    "images/hero/slide-8.png",
    "images/hero/slide-9.png",
]

SITE_SETTINGS_DEFAULTS = {
    "org_name": "Movement for Christ in Rwanda (MPCR)",
    "org_name_fr": "Mouvement Pour Christ au Rwanda",
    "footer_about": "Movement for Christ in Rwanda (MPCR) is a faith-based non-governmental organization committed to transforming communities through the Gospel, holistic health, sustainable landscape restoration, and economic self-reliance.",
    "legal_badge": "Legal Personality Compliance No. 166/2023 • Law No. 06/2012",
    "address_line_1": "Nyamirambo Sector, Nyarugenge District",
    "address_line_2": "Kigali City, Rwanda",
    "postal_box": "P.O. Box 1959, Kigali, Rwanda",
    "phone_primary": "(+250) 788 812 075",
    "phone_primary_raw": "+250788812075",
    "phone_secondary": "(+250) 788 436 988",
    "phone_secondary_raw": "+250788436988",
    "email_primary": "info@mouvementpourchriste.org",
    "email_secondary": "mchriste1992@gmail.com",
    "whatsapp_number": "250788812075",
    "whatsapp_message": "Hello MPCR, I would like to learn more about your programs and activities.",
    "facebook_url": "https://facebook.com",
    "instagram_url": "https://instagram.com",
    "twitter_url": "https://twitter.com",
    "focus_items": "Evangelism\nSocial (well being)\nEconomic\nDevelopment",
    "footer_copyright": "© 2026 Movement for Christ in Rwanda (MPCR) / Mouvement Pour Christ au Rwanda. All rights reserved.",
    "footer_tagline": '"A healthy spirit lives in a healthy body" — Roho nzima itura mu mubiri muzima',
    "social_handle": "@mpcr1990",
}
